Admin.Web.UI/Controllers/PartialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Admin.Web.UI.Controllers
{
    public class PartialController : Controller
    {
        // GET: Partial
        public PartialViewResult DrawerPartial()    // Layouttan burası tetiklenecek ve buradan drawerpartial viewına gidecek
        {
            var data = new List<string>();
            return PartialView("Partial/_DrawerPartial", data); //Bu metod layouttan çağrıldığında DrawerPartialview goruntusu return ile layoutta geri dönecek ve bu view layout içerisinde görünmüş olacak böylece drawer kısmı partial view ile taşınmıs oluyor.Partial view ile data(model) de gonderebiliyoruz.
        }
        public PartialViewResult HeaderPartial()    // HeaderPartial viewini donduren metod
        {
            return PartialView("Partial/_HeaderPartial");
        }
        public PartialViewResult ModalPartial()    // ModalPartial viewini donduren metod
        {
            return PartialView("Partial/_ModalPartial");
        }
    }
}

Admin.Web.UI/Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <title>@ViewBag.Title - WissenAkademie ASP.Net MVC</title>

    <meta name="description" content="AppUI - Admin Dashboard Template & UI Framework" />
    <meta name="author" content="rustheme" />
    <meta name="robots" content="noindex, nofollow" />  <!--Google ın bu sayfayı takip etmesini ve indexlemesini onluyor.-->
    <!-- Favicons -->
    <link rel="apple-touch-icon" href="~/assets/img/favicons/apple-touch-icon.png" />
    <link rel="icon" href="~/assets/img/favicons/favicon.ico" />

    <!-- Google fonts -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,400italic,500,900%7CRoboto+Slab:300,400%7CRoboto+Mono:400" />

    <!-- AppUI CSS stylesheets -->
    <link rel="stylesheet" id="css-font-awesome" href="~/assets/css/font-awesome.css" />
    <link rel="stylesheet" id="css-ionicons" href="~/assets/css/ionicons.css" />
    <link rel="stylesheet" id="css-bootstrap" href="~/assets/css/bootstrap.css" />
    <link rel="stylesheet" id="css-app" href="~/assets/css/app.css" />
    <link rel="stylesheet" id="css-app-custom" href="~/assets/css/app-custom.css" />
    @RenderSection("top", false)    <!--Üst tarafa bu sayfadakiler haricinde bir şey yazmak istersek diye bunu yazdık. RenderSection aracılığıyla başka bir viewde yazdığımız section burada gözükecek. Eğer true yaparsakta tüm sayfalarda bu sectionı kullanmamız gerekir ama bu şekilde sadece istediğimiz sayfalarda kullanacagız.-->
</head>
<body class="app-ui layout-has-drawer layout-has-fixed-header">
    <div class="app-layout-canvas">
        <div class="app-layout-container">
            <!-- Drawer -->
            @{Html.RenderAction("DrawerPartial", "Partial"); } <!--Partial Controllerında yer alan DrawerPartial metoduna gidecek-->
            <!-- End drawer -->
            <!-- Header -->
            @{Html.RenderAction("HeaderPartial", "Partial"); }
            <!-- End header -->
            <main class="app-layout-content">
                <!-- Page Content -->
                <div class="container-fluid p-y-md">
                    @RenderBody() <!-- Sayfanın orta kısmı ve sürekli degişecek kısmı -->
                </div>
                <!-- End Page Content -->
            </main>
        </div>
        <!-- .app-layout-container -->
    </div>
    <!-- .app-layout-canvas -->
    <!-- Apps Modal -->
    <!-- Opens from the button in the header -->
    @{Html.RenderAction("ModalPartial", "Partial"); }<!--Tıklayınca görünen ve sayfanın önünde açılır hale gelen pencereye modal denir. Normalde sayfanın altında ve gizlenmiş şekildedir. Gerekli yere tıklanınca tetiklenir.-->
    <!-- End Apps Modal -->
    <div class="app-ui-mask-modal"></div>
    <!-- AppUI Core JS: jQuery, Bootstrap, slimScroll, scrollLock and App.js -->
    <script src="~/assets/js/core/jquery.min.js"></script>
    <script src="~/assets/js/core/bootstrap.min.js"></script>
    <script src="~/assets/js/core/jquery.slimscroll.min.js"></script>
    <script src="~/assets/js/core/jquery.scrollLock.min.js"></script>
    <script src="~/assets/js/core/jquery.placeholder.min.js"></script>
    <script src="~/assets/js/app.js"></script>
    <script src="~/assets/js/app-custom.js"></script>

    @RenderSection("bottom", false)  <!--Alt tarafa bu sayfadakiler haricinde bir şey yazmak istersek diye bunu yazdık.-->
</body>
    </html>